"""
redact.py
---------
Defense-in-depth text scrubbing. Applied to EVERY piece of text (email
snippets, filenames, etc.) before it is (a) shown to the user in a summary
generated by an LLM, or (b) sent to the Claude API for ranking/summarizing.

This app is deliberately designed to never surface the *value* of a
sensitive identifier or secret — only to point the user at the email/file
that contains it, which they can open themselves in Gmail/Drive.
"""

import re

# PAN: 5 letters, 4 digits, 1 letter (e.g. ABCDE1234F)
_PAN_RE = re.compile(r"\b[A-Za-z]{5}[0-9]{4}[A-Za-z]\b")

# Aadhaar: 12 digits, optionally grouped in 4s with spaces or hyphens
_AADHAAR_RE = re.compile(r"\b\d{4}[\s-]?\d{4}[\s-]?\d{4}\b")

# Generic long digit runs (credit cards, account numbers, OTPs, etc.)
_LONG_DIGITS_RE = re.compile(r"\b\d{6,}\b")

# "password: xxxx" / "pwd - xxxx" / "pass=xxxx" style fragments
_PASSWORD_RE = re.compile(
    r"\b(pass(word)?|pwd|pin|otp|cvv)\b\s*[:=\-]?\s*\S+",
    re.IGNORECASE,
)

# Generic 8+ character tokens mixing letters/digits/symbols that look like
# a password or API key sitting in plain text.
_SECRET_LOOKING_RE = re.compile(
    r"\b(?=\S{10,})(?=\S*[a-z])(?=\S*[A-Z])(?=\S*\d)\S+\b"
)


def redact(text: str) -> str:
    """Mask anything that looks like a sensitive identifier or secret."""
    if not text:
        return text
    text = _PAN_RE.sub("[REDACTED-ID]", text)
    text = _AADHAAR_RE.sub("[REDACTED-ID]", text)
    text = _PASSWORD_RE.sub("[REDACTED-SECRET]", text)
    text = _LONG_DIGITS_RE.sub("[REDACTED-NUMBER]", text)
    text = _SECRET_LOOKING_RE.sub("[REDACTED-SECRET]", text)
    return text


# Queries the bot refuses outright, because there is no safe way to
# "search for and return" a secret without becoming a credential-harvesting
# tool. Keep this list conservative and easy to extend.
_BLOCKED_QUERY_RE = re.compile(
    r"\b(password|passwd|pwd|otp|cvv|pin\s*number|private\s*key|api\s*key|secret\s*key)\b",
    re.IGNORECASE,
)


def is_blocked_query(user_query: str) -> bool:
    return bool(_BLOCKED_QUERY_RE.search(user_query or ""))
